# Generated by Django 2.1.5 on 2019-01-12 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age_year', models.IntegerField()),
                ('age_day', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bodycondition',
            name='children',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link_sqlserver.Children'),
        ),
    ]
