# Generated by Django 2.1.5 on 2019-01-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_sqlserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodycondition',
            name='date',
            field=models.DateField(default='2019-01-12'),
        ),
    ]
