# Generated by Django 2.1.5 on 2019-01-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_sqlserver', '0002_bodycondition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='birthday',
            field=models.DateField(default='2019-1-12'),
            preserve_default=False,
        ),
    ]
