# Generated by Django 2.1.5 on 2019-01-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_sqlserver', '0003_children_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
